### PR TITLE
update element database

### PR DESCRIPTION
**Pull request by dericed**
This update the element list to the official list at https://raw.githubusercontent.com/cellar-wg/matroska-specification/master/ebml_matroska.xml, which adds some new elements for side-metadata and adjusts some elements which have been renamed. I'm uncertain why DisplayWidth and Display Height weren't here before but added them.

For reference to make the updated list I used:
```
wget https://raw.githubusercontent.com/cellar-wg/matroska-specification/master/ebml_matroska.xml
xmlstarlet select -N "e=https://ietf.org/cellar/ebml" -T -t -m "e:EBMLSchema/e:element" -o "  " -v "@id" -o ": (" -v @type -o ", \"" -v @name -o "\")," -n ebml_matroska.xml | sed 's|(master|(EET.MASTER|g;s|(uinteger|(EET.UNSIGNED|g;s|(integer|(EET.SIGNED|g;s|(utf-8|(EET.TEXTU|g;s|(string|(EET.TEXTA|g;s|(binary|(EET.BINARY|g;s|(float|(EET.FLOAT|g;s|(date|(EET.DATE|g'
```

But then manually edited Segment and Cluster to EET.JUST_GO_ON.

### CODE REVIEW

**Comment by vi** [comment]
It is also recommended to update `xml2mkv` tool's database, like in the [previous update commit](https://github.com/vi/mkvparse/commit/ab8a453dd814b90dd2590b2ab4a482e57e4b70fd).

**Comment by dericed** [comment]
Thanks, in working on this I got an error in the new elements, so putting this on hold until https://github.com/cellar-wg/matroska-specification/issues/371 is resolved.

**Comment by retokromer** [comment]
@dericed It’s resolved on the CELLAR end, if I am not wrong.

@vi Once this is updated and merged, could you possibly make a new release? I will then update the brew formula. 

Thank you very much both!

**Comment by vi** [comment]
> Once this is updated and merged, could you possibly make a new release?

Yes.

**Comment by dericed** [comment]
Hi @vi, please re-review. :)

**Comment by vi** [comment]
Tagged v1.2.0.

**Comment by retokromer** [comment]
@vi Thank you very much!

**Comment by vi** [comment]
Note: this pull request also renamed `Timecode` to `Timestamp` not completely. 
This resulted in incorrect timestamps being emitted by `mkvparse` and `xml2mkv`.

Published a point release: v1.2.1

**Comment by dericed** [comment]
ugh, apologies for contributing to that :(

**Pull request merged**
